baseURL = "https://hugo-blog-taupe.vercel.app/"
languageCode = "en-us"
title = "English Mania"
theme = "stack"

[params]
  mainSections = ["post"]
  customCSS = ["scss/custom.scss"]

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
