baseURL = "https://hugo-blog-taupe.vercel.app/"
languageCode = "en-us"
title = "English Learners"
theme = "stack"

[params]
  mainSections = ["ela","ep365","post"]
  customCSS = ["scss/custom.scss"]

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "ela"
    name = "ELA"
    url = "/ela/"
    weight = 2

  [[menu.main]]
    identifier = "ep365"
    name = "EnglishPod365"
    url = "/ep365/"
    weight = 3

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"
    weight = 4

  [[menu.main]]
	name = "Categories"
	url = "/categories/"

  [[menu.main]]
	name = "Tags"
	url = "/tags/"
	
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许在 Markdown 中使用原生 HTML
